### ISSUE TITLE
When conflicting counter/gauge names, only one counter/gauge will show up in Graphite

### ISSUE THREAD

**Issue by guavusAndrew** [graphite-project/graphite-web#1225] opened 2015-05-14 19:32 UTC
If inside the storage (/opt/graphite/storage/whisper)
we have a structure like this

/a/someCounter.wsp
/a.wsp

Only the first line (someCounter.wsp) will show up in Graphite UI as /a/someCounter
 "a.wsp" won't be visible in the UI.

In the application I am working on we have several with this issue as we have top level counters and then more detailed sub-counters. All the top level ones are missing from Graphite...

One solution is to rename all the conflicting counters to something unique. But it isn't always obvious that one isn't being rendered in Graphite until you are looking for it....

I'm using Graphite 0.9.10.

thanks!

**Comment by obfuscurity** [comment] 2015-05-14 19:53
This is a known issue but unfortunately probably won't get fixed anytime soon without a complete rewrite of the way the nodes are handled in the view. Closing as a duplicate of https://github.com/graphite-project/graphite-web/issues/193.

**Closed by obfuscurity** 2015-05-14 19:53 UTC
