### ISSUE TITLE
Graphite Login/Logout/Update Functions Don't Honor User's HTTP Protocol

### ISSUE THREAD

**Issue by colinbjohnson** [graphite-project/graphite-web#141] opened 2013-01-24 18:56 UTC
When running with the Graphite application behind a load balancer that decrypts https and directs to unencrypted graphite application the pages that are loaded after login, logout and update profile fail.

## Architecture described below:
1. load balancer answers for "https://graphite.mycompany.com" on port 443 (load balancer decrypts, sends to server)
2. server/graphite application answers http on port 80

## Steps to reproduce are described below:
1. connect to https://graphite.mycompany.com
2. click "login" button
3. login with correct credentials

## Desired Result of Login
4. After login, user is directed to use same protocol as was used when accessing login page - in this case: https://graphite.mycompany.com

## Actual Result of Login:
4. After login, user is directed to http://graphite.mycompany.com - this results in error as resource requested is http / port 80 - which load balancer is not answering for.

## Similar Issues
Login, Logout and Update exhibit similar behavior.

**Comment by obfuscurity** [comment] 2016-08-24 04:06
I believe this was an issue with older versions of Django. As our master branch is now [pinned to Django 1.9](https://github.com/graphite-project/graphite-web/blob/master/requirements.txt#L38), this shouldn't be an issue anymore. I'm personally unable to reproduce this issue with the master branch.

Closing this but if you can reproduce please let us know which versions of Graphite and Django and I'll be happy to investigate further.

**Closed by obfuscurity** 2016-08-24 04:06 UTC
