### ISSUE TITLE
[BUG]graphite render is error when REMOTE_RENDERING is True

### ISSUE THREAD

**Issue by ItWangS** [graphite-project/graphite-web#2580] opened 2020-04-10 10:01 UTC
**Describe the bug**
Internal Server Error: /render/
Traceback (most recent call last):
  File "/opt/graphite/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/graphite/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/graphite/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/errors.py", line 17, in new_f
    return f(*args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 155, in renderView
    response = renderViewGraph(graphOptions, requestOptions, data)
  File "/opt/graphite/webapp/graphite/render/views.py", line 173, in renderViewGraph
    image = delegateRendering(requestOptions['graphType'], graphOptions, requestOptions['forwardHeaders'])
  File "/opt/graphite/webapp/graphite/render/views.py", line 498, in delegateRendering
    postData = graphType + '\n' + pickle.dumps(graphOptions)
TypeError: must be str, not bytes

**Environment (please complete the following information):**
 - OS flavor:centos7
 - Graphite-web version 1.1.2
 - Django/Python version 3.0.5/3.6

**Comment by deniszh** [comment] 2020-04-10 17:41
Should be solved with
```python
try:
  import six.moves.cPickle as pickle
except ImportError:
  import pickle
```
Am I right, @piotr1212 ?

**Comment by ploxiln** [comment] 2020-04-10 20:40
I think the problem is that `graphType + '\n' + pickle.dumps(graphOptions)` is adding a string to a bytes. This wants bytes, maybe something like `(graphType + '\n').encode() + pickle.dumps(graphOptions)`

**Comment by piotr1212** [comment] 2020-04-12 21:39
@ploxiln did you check if the type of `graphType` is `string`? I'm not sure about that one, else seems fine.

**Comment by ploxiln** [comment] 2020-04-12 22:15
I just assumed, but checking now, I think `graphType` originates from:

```python
  ...
  graphType = queryParams.get('graphType','line')
  if graphType not in GraphTypes:
    raise AssertionError("Invalid graphType '%s', must be one of %s"
                         % (graphType,list(GraphTypes)))
  graphClass = GraphTypes[graphType]

  # Fill in the requestOptions
  requestOptions['graphType'] = graphType
  requestOptions['graphClass'] = graphClass
  ...
```

```python
GraphTypes = {
  'line' : LineGraph,
  'pie' : PieGraph,
}
```

```python
  if settings.REMOTE_RENDERING: # Rendering on other machines is faster in some situations
    image = delegateRendering(requestOptions['graphType'], graphOptions, requestOptions['forwardHeaders'])
```

so yeah must be `str`

**Comment by ItWangS** [comment] 2020-04-13 06:33
> Should be solved with
> 
> ```python
> try:
>   import six.moves.cPickle as pickle
> except ImportError:
>   import pickle
> ```
> 
> Am I right, @piotr1212 ?

in python3.6, pickle or cPikcle return bytes object
```shell
>>> import pickle
>>> from six.moves import cPickle
>>> type(cPickle.dumps({'line' : 'LineGraph'}))
<class 'bytes'>
>>> type(pickle.dumps({'line' : 'LineGraph'}))
<class 'bytes'>
```
in python2.7 return str
```shell
>>> import pickle
>>> type(pickle.dumps({'line' : 'LineGraph'}))
<type 'str'>
```

**Comment by piotr1212** [comment] 2020-04-13 07:09
Python 3 bytes are equal to python 2 str. Python 3 str is more like a
python 2 unicode ( but not exactly the same).

**Comment by ItWangS** [comment] 2020-04-13 08:33
look at the code:
```python
...
postData = (graphType + '\n').encode() + pickle.dumps(graphOptions)
...
try:
  connection.request('POST','/render/local/', postData, headers)
except six.moves.http_client.CannotSendRequest:
  connection = connector_class(server) #retry once
  connection.timeout = settings.REMOTE_RENDER_CONNECT_TIMEOUT
  connection.request('POST', '/render/local/', postData, headers)
...
```
it will call /render/local,
```python
def renderLocalView(request):
  try:
    start = time()
    reqParams = BytesIO(request.body)
    graphType = reqParams.readline().strip()
    optionsPickle = reqParams.read()
    reqParams.close()
    graphClass = GraphTypes[graphType]
    options = unpickle.loads(optionsPickle)
    image = doImageRender(graphClass, options)
    log.rendering("Delegated rendering request took %.6f seconds" % (time() -  start))
    response = buildResponse(image)
    add_never_cache_headers(response)
    return response
  except Exception:
    log.exception("Exception in graphite.render.views.rawrender")
    return HttpResponseServerError()
```
first, **graphType** is **bytes object**,it need decode
```python
graphType = reqParams.readline().strip().decode()
```
and, 
```python
options = unpickle.loads(optionsPickle)
```
I've got this exception:
```shell
Attempting to unpickle unsafe class Tags
```

**Comment by ploxiln** [comment] 2020-04-13 09:06
It does looks like `renderLocalView()` has another separate python3 str/bytes bug.

> Attempting to unpickle unsafe class Tags

Looks like this is from `graphite.util.SafeUnpickler` - maybe no one tested REMOTE_RENDERING with the new-ish tags feature? possible fix:

```diff
--- a/webapp/graphite/util.py
+++ b/webapp/graphite/util.py
@@ -162,7 +162,7 @@ if not PY3:
       'copy_reg': set(['_reconstructor']),
       '__builtin__': set(['object', 'list', 'set']),
       'collections': set(['deque']),
-      'graphite.render.datalib': set(['TimeSeries']),
+      'graphite.render.datalib': set(['TimeSeries', 'Tags']),
       'graphite.intervals': set(['Interval', 'IntervalSet']),
     }
 
@@ -196,7 +196,7 @@ else:
       'copy_reg': set(['_reconstructor']),
       'builtins': set(['object', 'list', 'set']),
       'collections': set(['deque']),
-      'graphite.render.datalib': set(['TimeSeries']),
+      'graphite.render.datalib': set(['TimeSeries', 'Tags']),
       'graphite.intervals': set(['Interval', 'IntervalSet']),
     }
```

(by the way, there should not be any need to change any pickle import)

**Comment by deniszh** [comment] 2020-04-13 10:02
Looks like it, @ploxiln ! Remote render is not very popular feature.
I will make a PR with all suggestions above.

**Comment by deniszh** [comment] 2020-04-13 20:42
Should be fixed in https://github.com/graphite-project/graphite-web/pull/2582, @ItWangS

**Closed** 2020-04-14 02:32 UTC
Labels: bug
