### ISSUE TITLE
web page Axis display issue

### ISSUE THREAD

**Issue by fudy** [graphite-project/graphite-web#1323] opened 2015-09-23 10:07 UTC
![graphite](https://cloud.githubusercontent.com/assets/4407739/10042479/db4952d6-621d-11e5-915e-0e37f04435e4.png)

**Comment by obfuscurity** [comment] 2015-09-23 11:37
Duplicate of https://github.com/graphite-project/graphite-web/issues/1191.

**Closed by obfuscurity** 2015-09-23 11:37 UTC
