### ISSUE TITLE
ImportError at /admin/events/event/

### ISSUE THREAD

**Issue by bryndin** [graphite-project/graphite-web#406] opened 2013-08-23 21:00 UTC
When I try to access the admin interface at 
```http://*my graphite server*/admin/events/event/```

I get ImportError at /admin/events/event/,  namely here
    ```from graphite.util import unpickle```

I wonder if it's a bug or I messed up some Graphite settings somewhere?

Here's the debug info:

```
ImportError at /admin/events/event/
cannot import name unpickle
Request Method:	GET
Request URL:	http://*my graphite server*/admin/events/event/
Django Version:	1.5.1
Exception Type:	ImportError
Exception Value:	
cannot import name unpickle
Exception Location:	/opt/graphite/webapp/graphite/whitelist/views.py in <module>, line 20
Python Executable:	/usr/bin/uwsgi
Python Version:	2.6.8
Python Path:	
['/opt/graphite/webapp',
 '.',
 '',
 '/usr/lib/python26.zip',
 '/usr/lib/python2.6',
 '/usr/lib/python2.6/plat-linux2',
 '/usr/lib/python2.6/lib-tk',
 '/usr/lib/python2.6/lib-old',
 '/usr/lib/python2.6/lib-dynload',
 '/usr/lib/python2.6/site-packages',
 '/usr/lib/python2.6/site-packages/PIL',
 '/usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info',
 '/opt/graphite/webapp/graphite/thirdparty']
```

**Comment by obfuscurity** [comment] 2016-07-08 19:09
@bryndin My sincere apologies for the length of delay in responding to your issue. I haven't been able to identify the specific fix, but I'm pretty sure this was already resolved some time ago. I'm unable to reproduce this with Graphite 0.9.15.

If you are indeed still encountering this exception please let us know, but for now I'm going to assume it's no longer relevant and close this issue.

**Closed by obfuscurity** 2016-07-08 19:09 UTC
