### ISSUE TITLE
/events/get_data fails to return events with tag names having more than so many characters

### ISSUE THREAD

**Issue by scosist** [graphite-project/graphite-web#1635] opened 2016-08-02 10:15 UTC
Attempted to retrieve event by tag name without success. I tested with two different tags that both exist as events. One is 49 characters long and the other, 54. The former is returned, the latter is not.

`curl 'http://graphite/events/get_data?tags=tag_name_that_is_forty_nine_characters_long_truly'`

````
[{"data": "ok", "what": "sensu_event", "when": 1469951917.0, "id": 2, "tags": "tag_name_that_is_forty_nine_characters_long_truly"}]
````

`curl 'http://graphite/events/get_data?tags=tag_name_that_is_longer_than_forty_nine_characters_long'`

```
[]
```

Both are returned by `curl 'http://graphite/events/get_data'`
```
[{"data": "warning", "what": "sensu_event", "when": 1469950417.0, "id": 1, "tags": "tag_name_that_is_longer_than_forty_nine_characters_long"}, {"data": "ok", "what": "sensu_event", "when": 1469951917.0, "id": 1, "tags": "tag_name_that_is_longer_than_forty_nine_characters_long"}]
```

Is there some kind of character limitation at 50 characters or so that is preventing the specific tag to be retrieved by name?

Using graphite-web debian package 0.9.12+debian-6

**Comment by deniszh** [comment] 2016-08-02 11:12
Which backend do you use for Django, @scosist? Default one, SQLite? Just shooting in the dark, though.

**Comment by obfuscurity** [comment] 2016-08-02 11:38
Is this a duplicate of #1210?

**Comment by scosist** [comment] 2016-08-02 15:23
@deniszh I'm using postgresql as a backend here.

@obfuscurity I wouldn't say this is a duplicate of #1210. I don't think it's even related. This is a problem of failing to retrieve an event given a tag, due to the character length of the tag it seems. #1210 is a problem where events are returned when only some (IOW not all) of the tags match.

**Comment by obfuscurity** [comment] 2016-08-08 16:52
Looks like django-tagging has a default `MAX_TAG_LENGTH` of 50 characters. This can be overridden by adding `MAX_TAG_LENGTH=255` to your `local_settings.py` and restarting the Graphite webapp.

http://django-tagging.readthedocs.io/en/develop/#max-tag-length

**Closed** 2016-08-08 17:06 UTC
