### ISSUE TITLE
Timezone and absolute time range 

### ISSUE THREAD

**Issue by torkelo** [graphite-project/graphite-web#639] opened 2014-02-26 08:18 UTC
I am unable to get the tz parameter to have any effect on the time range filter. It seems to only change the time axis on the rendered image. 

Example:

/render?from=07:00_20140226&until=08:00_20140226&width=400&height=250&target=carbon.agents.graphite.metricsReceived

![image](https://f.cloud.github.com/assets/10999/2267733/ed2d365e-9ebd-11e3-8ea7-042d66626344.png)

Here I do not have a tz parameter, the from parameter 07:00_20140226 is handled with the default timezone (set in local_settings.py) and the time axis is also shown in the default timezone (Europe/Berlin).

Example2:

/render?from=07:00_20140226&until=08:00_20140226&width=400&height=250&target=carbon.agents.graphite.metricsReceived&tz=America/New_York

![image](https://f.cloud.github.com/assets/10999/2267741/0dc62920-9ebe-11e3-9d42-f7aa8a932e83.png)

This image shows the same data, but the time axis shows time in America/New_York timezone, I would expect that the time range "from" parameter also would be parsed as America/New_York and that the graph would change to reflect a completely different time range. 

The problem I have is with [Grafana](https://github.com/torkelo/grafana), an alternate frontend for graphite. Users located in different time zones cannot zoom (i.e use absolute time ranges). I would like to send the from and until parameter in their local time zone and have graphite translate it. 

Looking at render/views.py  it looks like from and until is parsed using parseATTime but somehow it is not having any effect when fetching data for the series.

**Comment by Comradin** [comment] 2015-04-01 11:33
Any chance, this will be fixed in 0.9.13?

**Comment by deniszh** [comment] 2015-04-01 12:12
@Comradin, 
IIRC it's already done in https://github.com/graphite-project/graphite-web/pull/989 and later fixes.

**Comment by Comradin** [comment] 2015-04-01 13:56
Hmm, but why is this issue then still open if it is fixed in master?
Any news on when 0.9.13 will finally arrive?

**Comment by deniszh** [comment] 2015-04-01 13:58
Good question. Maybe nobody checked if issue is really gone in master / 0.9.x ?
@torkelo, could you please test it?

And please note that master and 0.9.x is different branches.

**Comment by obfuscurity** [comment] 2015-10-01 13:17
@torkelo would you be so kind as to test this against 0.9.x and see if the issue is resolved for you?

**Comment by torkelo** [comment] 2015-10-01 13:45
@obfuscurity seems to be working. This is not an issue for Grafana any more, as Grafana switched to using epochs in the from and until parmas

**Comment by obfuscurity** [comment] 2015-10-01 13:49
Thanks @torkelo.

**Closed by obfuscurity** 2015-10-01 13:49 UTC

**Comment by Dieterbe** [comment] 2017-07-06 13:33
i'm looking into this more , using graphite 1.0.1 and I can report that while this bug is indeed fixed (e.g. date specification is interpreted in the timezone) when specifying timezone with a `HH:MM_YYYMMDD` pattern, it does not work when using other `at`-style patterns, such as `noon`. see examples below. (default TZ is set up to UTC)

## patterns it does work with.

`target=carbon.agents.b2dd5129e459-a.updateOperations&from=08:00_20170706&tz=America/New_York`
![tz3](https://user-images.githubusercontent.com/20774/27912961-dbecb820-625e-11e7-8b5f-10744be35dcb.png)
`target=carbon.agents.b2dd5129e459-a.updateOperations&from=08:00_20170706`
![tz4](https://user-images.githubusercontent.com/20774/27912959-dbe5242a-625e-11e7-9e3a-f1ff1a5b2411.png)

## patterns it does not work with

as originally reported, here the TZ just controls the timestamps returned, it does not control how the data specification is interpreted (thus, which data is fetched)
`target=carbon.agents.b2dd5129e459-a.updateOperations&from=noon&tz=America/New_York`


![tz1](https://user-images.githubusercontent.com/20774/27912957-dbe283b4-625e-11e7-8273-799823610450.png)
`target=carbon.agents.b2dd5129e459-a.updateOperations&from=noon`
![tz2](https://user-images.githubusercontent.com/20774/27912960-dbe7075e-625e-11e7-9777-1c5eb6731738.png)
