### ISSUE TITLE
drawAsInfinite horizontal rendering issue

### ISSUE THREAD

**Issue by mattpascoe** [graphite-project/graphite-web#36] opened 2012-08-08 20:46 UTC
I am observing two issues with `drawAsInfinite`.  I see that the Infinite line is drawn at position 0 (horizontally along the bottom) as well as vertically in the graph at the proper location.  If at all possible, it would be nice to have infinite lines only draw vertically.  If one chooses to use a larger `lineWidth` it causes an even more distinct horizontal line to be drawn which can obscure other information.

I believe a similar rendering issue exists for `drawAsInfinite` as outlined in #31 for all types of `areaModes`.   On my graphs that are zoomed in fairly close, and are non stacked graphs I see a small gap in the horizontal line that is drawn.  The gap is just to the right of the vertical line and shows up for around a minutes worth of time.  If my first issue is resolved then this second observation becomes moot.

**Comment by cbowman0** [comment] 2016-07-27 19:40
I was able to reproduce in master and it does go away if `drawNullAsZero` is not set to 1.

I'm unsure if the side effect of `drawNullAsZero=1` on events is ok.

**Comment by obfuscurity** [comment] 2016-07-28 13:33
Ok, this is not a bug as far as I can see. `drawNullAsZero` is having the [desired effect](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/glyph.py#L1283-L1284) of converting null datapoints in the series to 0. Because 0 is not null, it gets a point rendered.

If you want to avoid this effect on any `drawAsInfinite` series, you should not use `drawNullAsZero` (a graph-level parameter) and instead use the per-series `transformNull` function on the remaining series.

@cbowman0 sound right to you?

**Comment by cbowman0** [comment] 2016-07-28 13:44
Yes.

**Comment by obfuscurity** [comment] 2016-07-28 13:58
Ok, closing this out. Apologies for the _very_ long time-to-resolution but hopefully this makes sense now.

**Closed by obfuscurity** 2016-07-28 13:58 UTC
Labels: bug
