### ISSUE TITLE
Carbon cache Baseline 

### ISSUE THREAD

**Issue by ravibhooshan** [graphite-project/graphite-web#1452] opened 2016-01-15 15:27 UTC
Hi - Its not an issue just wanted to know about performance baseline.
I am running carbon-c-relay using consistency hashing which is sending data to child carbon-c-relay and child relay is sending data to carbon cache.
I am seeing each carbon-cache starts dropping data once the cross 600k metric per minutes.
I am using default settings for carbon.conf.
MY carbon cache servers are running RHEL6, 64GB RAM and 24 core CPU.

Please suggest how can I increase 600k limit of cache cache.
(https://cloud.githubusercontent.com/assets/11981903/12356760/3f6bd93e-bb72-11e5-8f4e-5684daf3386c.png

**Comment by obfuscurity** [comment] 2016-01-15 15:36
I assume you're hitting the performance limitations of your particular configuration. The short answer is to decrease your I/O bottleneck by increasing the number of carbon-cache processes and putting a carbon-relay in front of them; or in your case, having your carbon-c-relay distribute among your carbon-cache pool.

I'm closing this issue since this is not a bug, but I encourage you to post your question to https://answers.launchpad.net/graphite which is more suitable for community/support discussions at length. Thank you.

**Closed by obfuscurity** 2016-01-15 15:36 UTC
