### ISSUE TITLE
could not accept new connection (EMFILE)

### ISSUE THREAD

**Issue by boopathi** [graphite-project/graphite-web#108] opened 2012-11-27 10:54 UTC
Using carbon-relay and 3 instances of carbon-cache behind it. Sending metrics via TCP. 

Problem with the twisted daemon. Increasing ulimit doesn't seem to suffice the need. 
Restart temporarily fixes issue, and number of open file descriptors gets gobbled up and this error appears.

**Comment by wldevries** [comment] 2016-06-26 14:15
Duplicate of https://github.com/graphite-project/carbon/issues/428

**Comment by obfuscurity** [comment] 2016-06-26 14:27
Indeed, this is a duplicate. It's also not a graphite-web bug so we'll track it in the other issue.

**Closed by obfuscurity** 2016-06-26 14:27 UTC
