### ISSUE TITLE
django-tagging 0.4 does not work with graphite, be more specific

### ISSUE THREAD

**Issue by jblaine** [graphite-project/graphite-web#1541] opened 2016-06-14 20:51 UTC
django-tagging 0.4+ does not work with graphite 0.9.15 and Django 1.4.x or 1.5.x

version 0.3.6 is required

- [ ] pin django-tagging==0.3.6 in requirements.txt for 0.9.x branch for a 0.9.16 release?
- [ ] document?

**Comment by deniszh** [comment] 2016-06-14 22:35
We have https://github.com/graphite-project/graphite-web/blob/0.9.x/requirements.txt
We could change `django-tagging==0.3.1` to `django-tagging>=0.3.1,<0.4` but not sure if needed.
We also have `django-tagging<0.4` in https://github.com/graphite-project/graphite-web/blob/0.9.x/.travis.yml

**Comment by obfuscurity** [comment] 2016-09-14 02:14
Note that we're no longer evolving the `0.9.x` branch except in rare circumstances. Django-tagging has been pinned to version 0.4.3 in the `master` branch and it works as intended. Closing this issue.

**Closed by obfuscurity** 2016-09-14 02:14 UTC
